// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wejick/gchain/model"
)

// LLMModel is an autogenerated mock type for the LLMModel type
type LLMModel struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, prompt, options
func (_m *LLMModel) Call(ctx context.Context, prompt string, options ...func(*model.Option)) (string, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = 