
// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package textsplitter

import (
	"github.com/wejick/gchain/document"
	"sync"
)

// Ensure, that TextSplitterMock does implement TextSplitter.
// If this is not the case, regenerate this file with moq.
var _ TextSplitter = &TextSplitterMock{}

// TextSplitterMock is a mock implementation of TextSplitter.
//
//	func TestSomethingThatUsesTextSplitter(t *testing.T) {
//
//		// make and configure a mocked TextSplitter
//		mockedTextSplitter := &TextSplitterMock{
//			LenFunc: func(input string) int {
//				panic("mock out the Len method")
//			},
//			SplitDocumentFunc: func(input document.Document, maxChunkSize int, overlap int) []document.Document {
//				panic("mock out the SplitDocument method")
//			},
//			SplitTextFunc: func(input string, maxChunkSize int, overlap int) []string {
//				panic("mock out the SplitText method")
//			},
//		}
//
//		// use mockedTextSplitter in code that requires TextSplitter
//		// and then make assertions.
//
//	}
type TextSplitterMock struct {
	// LenFunc mocks the Len method.
	LenFunc func(input string) int

	// SplitDocumentFunc mocks the SplitDocument method.
	SplitDocumentFunc func(input document.Document, maxChunkSize int, overlap int) []document.Document