// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wejick/gchain/model"
)

// CombinedDocument is an autogenerated mock type for the CombinedDocument type
type CombinedDocument struct {
	mock.Mock
}

// Combine provides a mock function with given fields: ctx, docs, options
func (_m *CombinedDocument) Combine(ctx context.Context, docs []string, options ...func(*model.Option)) (string, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, docs)
	_ca = append(_ca, _va