// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	datastore "github.com/wejick/gchain/datastore"
	document "github.com/wejick/gchain/document"

	mock "github.com/stretchr/testify/mock"
)

// VectorStore is an autogenerated mock type for the VectorStore type
type VectorStore struct {
	mock.Mock
}

// AddDocuments provides a mock function with given fields: ctx, indexName, documents
func (_m *VectorStore) AddDocuments(ctx context.Context, indexName string, documents []document.Document) ([]error, error) {
	ret := _m.Called(ctx, indexName, documents)

	var r0 []error
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []document.Document) ([]error, error)); ok {
		return rf(ctx, indexName, documents)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []document.Document) []error); ok {
		r0 = rf(ctx, indexName, documents)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []document.Document) error); ok {
		r1 = rf(ctx, indexName, documents)
	} e